---
name: Release

on:
    push:
        tags:
            - '*'

jobs:
    release-pypi:
        name: release-pypi
        runs-on: ubuntu-latest
        environment:
            name: pypi
            url: https://pypi.org/p/oocone
        permissions:
            id-token: write

        steps:
            - name: Checkout
              uses: actions/checkout@v5
              with:
                  # Fetch the whole history to ensure that the right version is derived from history
                  fetch-depth: 0
            - name: Set up PDM
              uses: pdm-project/setup-pdm@main
              with:
                  python-version: '>=3.13.2'
                  cache: true
            - name: Build artifacts
              run: |
                  pip install build
                  python -m build
            - name: Test Build
              run: |
                  python3 -m venv fresh_env
                  . fresh_env/bin/activate
                  pip install dist/*.whl
            - name: Publish package distributions to PyPI
              uses: pypa/gh-action-pypi-publish@release/v1
